### ISSUE TITLE
Fix rendering of README.md

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/DTIAtlasBuilder#19]
![image](https://user-images.githubusercontent.com/219043/48296565-33b38400-e466-11e8-9819-c52884cef621.png)

**Comment by juanprietob** [comment]
Fixed!

**Comment by adrienkaiser** [comment]
I added the missing image back to the repo.

**Comment by jcfr** [comment]
Well done @juanprietob and @adrienkaiser :tada:
